### ISSUE TITLE
 Unknown column 'created_at'

### ISSUE THREAD

**Issue by postmodern** [leesmith/ticket_mule#13]
Just did a fresh install of ticket_mule, and got this mysql error:

```
ActiveRecord::StatementInvalid (Mysql::Error: Unknown column 'created_at' in 'having clause': SELECT count(*) AS count_all, date(created_at) AS date_created_at FROM `tickets`  GROUP BY date(created_at)  HAVING date(created_at) >= '2011-04-13' and date(created_at) <= '2011-05-12' ):
  app/models/ticket.rb:28:in `timeline_opened_tickets'
  app/controllers/dashboard_controller.rb:12:in `index'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

**Comment by postmodern** [comment]
Patch:

```
diff --git a/app/models/ticket.rb b/app/models/ticket.rb
index 7051d1f..40e898b 100644
--- a/app/models/ticket.rb
+++ b/app/models/ticket.rb
@@ -25,11 +25,11 @@ class Ticket < ActiveRecord::Base
   named_scope :closed_tickets, :limit => 5, :joins => :status, :include => [:creator, :owner, :group, :status, :priority], :conditions => ['

   def self.timeline_opened_tickets
-    self.count(:group => 'date(created_at)', :having => ['date(created_at) >= ? and date(created_at) <= ?', (Time.zone.now.beginning_of_day 
+    self.count(:group => 'date(created_at)', :having => ['date_created_at >= ? and date_created_at <= ?', (Time.zone.now.beginning_of_day - 
   end

   def self.timeline_closed_tickets
-    self.count(:group => 'date(closed_at)', :having => ['date(closed_at) >= ? and date(closed_at) <= ?', (Time.zone.now.beginning_of_day - 3
+    self.count(:group => 'date(closed_at)', :having => ['date_closed_at >= ? and date_closed_at <= ?', (Time.zone.now.beginning_of_day - 30.
   end

   def closed?
```

**Comment by ghost** [comment]
This is covered in the "Database Support" section of the README.
